name: Test schedule

on:
  schedule:
    # TEST: prova a partire ogni 5 minuti
    - cron: "*/5 * * * *"

  workflow_dispatch:

jobs:
  test-schedule:
    runs-on: ubuntu-latest

    steps:
      - name: Print schedule test
        run: |
          echo "Test schedule partito correttamente."
          echo "Ora UTC:"
          date -u
          echo "Ora runner:"
          date
